### ISSUE TITLE
Zeroed out confusion matrix and AUC = 0 during training when trained with gradable images only

### ISSUE THREAD

**Issue by bsabri** [mikevoets/jama16-retina-replication#8] opened 2019-03-06 08:21 UTC
I'm observing the same issue reported in #6 when I train with gradable images only. When all eyepacs images are used this does not happen

**Comment by ZHULLI** [comment] 2019-03-07 00:44
@bsabri Hello, I am also doing DR, can you tell me how to do it in data preprocessing? I have a dataset but only when the eyepacs.sh is running, the training set is not preprocessed.

**Comment by mikevoets** [comment] 2019-06-05 13:16
@bsabri Does this happen every time you train? Or only occasionally?

@ZHULLI What is the exact command you're running? And on what platform?

**Comment by mikevoets** [comment] 2019-12-02 09:00
Closing this issue for now because I didn't receive enough information to reproduce this issue.

**Closed as completed by mikevoets** 2019-12-02 09:00 UTC
